const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');

/**
 * Generates a formal RFP PDF document from RFP data.
 * @param {Object} rfp - The RFP object containing title, user_prompt, and structured_data.
 * @returns {Promise<Buffer>} - The generated PDF as a buffer.
 */
exports.generateRFPPDF = async (rfp) => {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 800]);
    const { width, height } = page.getSize();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let yOffset = height - 50;

    // Header
    page.drawText('Request for Proposal (RFP)', {
        x: 50,
        y: yOffset,
        size: 20,
        font: boldFont,
        color: rgb(0, 0, 0),
    });
    yOffset -= 30;

    // Title
    page.drawText(`Title: ${rfp.title || 'Untitled RFP'}`, {
        x: 50,
        y: yOffset,
        size: 14,
        font: boldFont,
    });
    yOffset -= 25;

    // Metadata
    page.drawText(`Date: ${new Date(rfp.createdAt).toLocaleDateString()}`, {
        x: 50,
        y: yOffset,
        size: 10,
        font: font,
    });
    yOffset -= 15;
    page.drawText(`Status: ${rfp.status}`, {
        x: 50,
        y: yOffset,
        size: 10,
        font: font,
    });
    yOffset -= 30;

    // Requirements Section
    page.drawText('Requirements:', {
        x: 50,
        y: yOffset,
        size: 12,
        font: boldFont,
    });
    yOffset -= 20;

    const lines = (rfp.user_prompt || '').split('\n');
    for (const line of lines) {
        if (yOffset < 50) {
            // Very basic page overflow handling (just for now)
            break;
        }
        page.drawText(line, {
            x: 50,
            y: yOffset,
            size: 10,
            font: font,
            maxWidth: 500,
            lineHeight: 12,
        });
        yOffset -= 15;
    }

    yOffset -= 20;

    // Structured Info (Summary)
    if (rfp.structured_data) {
        page.drawText('Structured Data Summary:', {
            x: 50,
            y: yOffset,
            size: 12,
            font: boldFont,
        });
        yOffset -= 20;

        const data = rfp.structured_data;
        const details = [
            `Timeline: ${data.timeline || 'N/A'}`,
            `Budget: ${data.budget || 'N/A'}`,
            `Payment Terms: ${data.payment_terms || 'N/A'}`,
            `Warranty: ${data.warranty_requirements || 'N/A'}`,
        ];

        for (const detail of details) {
            page.drawText(detail, {
                x: 50,
                y: yOffset,
                size: 10,
                font: font,
            });
            yOffset -= 15;
        }
    }

    // Footer
    page.drawText('Generated by RFP AI System', {
        x: 50,
        y: 40,
        size: 8,
        font: font,
        color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
};
